language: node_js
node_js:
  - "5.10.1"
before_script:
  - npm install -g gulp
after_script:
  - cat ./spec/coverage/**/*.info | node ./node_modules/coveralls/bin/coveralls.js
addons:
  firefox: "latest"
